{
 "title": "PetAdoptions Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "BaniluxService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of pets adopted vs searched",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(adot_baniluxsvc_petadoptions_total[15m])/rate(adot_baniluxsvc_petsearches_total[15m]))* 100"
    }
   ]
  },
  {
   "title": "Total searches for pets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "adot_baniluxsvc_petsearches_total"
    }
   ]
  },
  {
   "title": "Rate of Puppy searches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(adot_baniluxsvc_pet_puppy_searches_total[15m])/rate(adot_baniluxsvc_petsearches_total[15m]))*100"
    }
   ]
  },
  {
   "title": "Rate of Bunny searches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(adot_baniluxsvc_pet_bunny_searches_total[15m])/rate(adot_baniluxsvc_petsearches_total[15m]))*100"
    }
   ]
  },
  {
   "title": "Rate of Kitten searches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(adot_baniluxsvc_pet_kitten_searches_total[15m])/rate(adot_baniluxsvc_petsearches_total[15m]))*100"
    }
   ]
  },
  { "title": "PetListAdoptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "List adoptions requests rate",
   "type": "graph",
   "description": "Total request for health check and adoption list endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(petlistadoptions_requests_total[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "List adoptions service p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(petlistadoptions_requests_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "List adoptions CPU utilization percent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecs_task_cpu_usage_vcpu*100)/ ecs_task_cpu_reserved",
     "legendFormat": " {{aws_ecs_task_id}}"
    }
   ]
  },
  {
   "title": "List adoptions memory utilization percent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecs_task_memory_utilized*100)/ ecs_task_memory_reserved",
     "legendFormat": " {{aws_ecs_task_id}}"
    }
   ]
  }
 ]
}