apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: grafana-repo
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/Eric-YJi/one-observability-demo
  ref:
    branch: main
